apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-postgres
  labels:
    db: my-postgres
spec:
  selector:
    matchLabels:
      db: my-postgres
  template:
    metadata:
      labels:
        db: my-postgres
    spec:
      containers:
        - name: my-postgres
          image: postgres:14.4
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres 
 
          resources:
            requests:
              cpu: 100m
              memory: 60Mi
            limits:
              cpu: 200m
              memory: 120Mi

---

apiVersion: v1
kind: Service
metadata:
  name: my-postgres
  labels:
    db: my-postgres
spec:
  type: ClusterIP
  selector:
    db: my-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432