apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  labels:
    ms: my-rabbitmq
data:
  rabbitmq.conf: |
    default_user=rabbit
    default_pass=rabbit


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-rabbitmq
  labels:
    messaging: my-rabbitmq
spec:
  selector:
    matchLabels:
      messaging: my-rabbitmq
  template:
    metadata:
      labels:
        messaging: my-rabbitmq
    spec:
      containers:
        - name: my-rabbitmq
          image: rabbitmq:3.10-management
         
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 200m
              memory: 100Mi
          volumeMounts:
            - mountPath: /etc/rabbitmq
              name: rabbitmq-config-volume

      volumes:
        - name: rabbitmq-config-volume
          configMap: 
            name: rabbitmq-config

---

apiVersion: v1
kind: Service
metadata:
  name: my-rabbitmq
  labels:
    messaging: my-rabbitmq
spec:
  type: ClusterIP
  selector:
    db: my-rabbitmq
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672