version: "3.8"
services:
  
  auth-service:
    image: "auth-service:1.0"
    container_name: "auth-service"
    ports:
      - 9000:9000
    environment:
      - BPL_JVM_THREAD_COUNT=50
  
  config-service:
    image: "config-service:1.0"
    container_name: "config-service"
    ports:
      - 9001:9001
    environment:
      - BPL_JVM_THREAD_COUNT=50  
  
  redis:
    image: "redis:7.0"
    container_name: "redis"
    ports:
      - 6379:6379
  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
  
  app-service:
    depends_on:
      - redis
    image: "app-service:1.0"
    container_name: "app-service"
    ports:
      - 8080:8080
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_CLOUD_CONFIG_URI=http://config-service:9001
      - SPRING_PROFILES_ACTIVE=containerenv
         
  invoice-service:
    depends_on:
      - postgres-db
    image: "invoice-service:1.0"
    container_name: "invoice-service"
    ports:
      - 8081:8081
      - 5001:5001
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=5001
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/invoiceservice
      - SPRING_CLOUD_CONFIG_URI=http://config-service:9001
      - SPRING_PROFILES_ACTIVE=proddata
  
  payment-service:
    depends_on:
      - invoice-service
      - postgres-db
      - rabbitmq
    image: "payment-service:1.0"
    container_name: "payment-service"
    ports:
      - 8082:8082
      - 5002:5002
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=5002
      - SPRING_DATASOURCE_URL=r2dbc:postgresql://postgres-db:5432/paymentService
      - SPRING_CLOUD_CONFIG_URI=http://config-service:9001
      - CONFIG_INVOICE-SERVICE-URI=http://invoice-service:8081
      - RABBITMQ_HOST=rabbitmq
      - SPRING_PROFILES_ACTIVE=proddata
  notification-service:
    depends_on:
      - rabbitmq
    image: "notification-service:1.0"
    container_name: "notification-service"
    ports:
      - 9000:9000
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - SPRING_CLOUD_CONFIG_URI=http://config-service:9001
      - RABBITMQ_HOST=rabbitmq
 
  postgres-db:
    image: "postgres:14.4"
    container_name: "postgres-db"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql