version: "3.8"
services:
  
  config-service:
    image: "config-service:1.0"
    container_name: "config-service"
    ports:
      - 9001:9001
    environment:
      - BPL_JVM_THREAD_COUNT=50  
  
  invoice-service:
    depends_on:
      - postgres-db
    image: "invoice-service:1.0"
    container_name: "invoice-service"
    ports:
      - 8080:8080
      - 5001:5001
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=5001
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/invoiceService
      - SPRING_CLOUD_CONFIG_URI=http://config-service:9001
      - SPRING_PROFILES_ACTIVE=proddata
  
  payment-service:
    depends_on:
      - invoice-service
      - postgres-db
    image: "payment-service:1.0"
    container_name: "payment-service"
    ports:
      8081:8081
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - SPRING_DATASOURCE_URL=r2dbc:postgresql://postgres-db:5432/paymentService
      - SPRING_CLOUD_CONFIG_URI=http://config-service:9001
  
  
  postgres-db:
    image: "postgres:14.4"
    container_name: "postgres-db"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql